# Aliases
alias pamcan=pacman
alias cd=z
alias ls=exa
alias sail='sh $([ -f sail ] && echo sail || echo vendor/bin/sail)'
alias vim=nvim
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -v'
alias gd='git diff'
alias gst='git status'
alias gco='git checkout'
alias gb='git branch'
alias gp='git push'
alias gpl='git pull --rebase'
alias gf='git fetch'
alias start-vpn='sudo systemctl start openvpn-client@client'
alias stop-vpn='sudo systemctl start openvpn-client@client'
alias wine64=wine
